name: kratos_iq
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  shadcn_flutter: ^0.0.36
  just_audio: ^0.10.3
  dio: ^5.8.0+1
  flutter_webrtc: ^0.14.1
  web_socket_channel: ^3.0.3
  video_player: ^2.10.0
  intl: ^0.20.2
  firebase_core: ^3.13.1
  url_launcher_web: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter_28pt-ExtraBold.ttf
          weight: 800
